import type { Metadata } from "next";
import { Onest, Roboto } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import "./assets/globals.css";
import ParticleBg from "../components/particleBg";
import Header from "@/components/header/header";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang="en">
      <body
        style={{
          scrollbarColor: "var(--color-divider) var(--color-background-paper)"
        }}
        className={`${onest.variable} bg-background-default text-text font-onest relative h-screen antialiased`}
      >
        <NextIntlClientProvider>
          <div className="flex h-full w-full flex-col">
            <Header />
            <ParticleBg />
            <main className="relative z-10 h-full w-full overflow-hidden">
              {children}
            </main>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
