name: Deploy to Ubuntu Cloud Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run deployment commands on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER}}
          password: ${{ secrets.SERVER_KEY }}
          script: sudo docker stop portfolio