name: Deploy to Ubuntu Cloud Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run deployment commands on server
        uses: appleboy/ssh-action@v1
        with:
          host: 45.138.135.100
          username: root
          password: 3p5Vs82cLD
          script: sudo docker stop nextjs-docker